services:
  db:
    image: postgres:latest
    restart: always
    container_name: e_pharmacy_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postg  res
      POSTGRES_DB: epharmacy
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data:
